branches:
  only:
    - master

language: python

script: python setup.py test

install:
  - python -m pip install -r requirements.txt
  - python setup.py build sdist bdist_wheel

deploy:
  - provider: pypi
    user: jduncan
    password:
      secure: gDKmV0qwRpFiDAwQD9YKbZ5SMnbgRK2qOwcqrRlWHxEtnzpazjk9XB/PPk2LBmpEgwPccqR5yEETtnavdl0o/oXc9bas6XEP4sIAc/V0nkzpIizdt6QRPHn+EWtVjuWJaD/ROGB9K/n3JSj5C39ypRcc6A0+6KXHx8KkgNtyjzYoUuH0o3GVjreJ9TEZ2i8oSy0JKQK1MAAVPUy5lST2fjLbDq/VhO5b5AepAveM2/0XJHfunSt7D+51AO58nfE1wArOp1Std8jo8An/Fe9+HJ2MLCyM94Lp6R1eRj2Dq6COwM9u5089/xXxaKh12Yv6zKlvPmcbeGGaMcnxMNVMf3brNMwLsdfRtKNTL8/Rn3v+ujn70XC7jQII874BOYv5/ohJnID4THkl1e4YhIPSGq8Z/PP4vtTfKxu+3Kx69bBECUPaXim8a+hgAxa/gkh+boMq4lNQxoDz2VO+HYiFUajfvXpfCwmR55ZpfAihieuv0a6q89gjeD5aSg5oVKXwHswPOUbxMaH8BSn1mGp67f3TtPYTPUe/dTiqC6x2pRuFyNHnR6SCTKqVZY2X5CIt9FNqForiOMb5yv8ZSC7QjED4wvguI9ln/1DLuqYhnu/xoPDM3ByYbs5iHg7Ool1bZzT500eyvj1rTGFkTNfLojULvXVe0ZPe00/0tWIRaRo=
    server: https://test.pypi.org/legacy/
  - provider: pypi
    user: jduncan
    password:
      secure: sCiOXJGAGU6a/0E7zuhR/Iw1nrc2kIy7K5PhcI+dFE+Rd0KvDJKhqU7Ec7mTxoATu6vnk3k2bBN7B1+bEt867LNGSa6u7dJioI04Pbo/zG35RLl8h4AZBR8/luXChCKYV6Vuzkh3OSTlg1vHtvz8YItrGWqNMqlu0k+LXo+GUrhN3XaDtYvNlZumL9VAupBsqT+NLxykAx70lBaf+iLrMOuTBhMWVt4btj/kqFJHFFnxL6h+vJn3szi/kVofO2omsPX+5188fBoewAMsP13dX30sENMDAt2Mh1PRarZaz95/LmcLuLby8kaa8W1j6h9RBZef90PYpXtEsSvMUn79Z3ZuCpDDWK59oyB5S6szUtqVXkSt2LPm8a7xT3MllDHBWUWd6sauGjSsvLaBQCWD3T7+Lp+IA5E1Eulfa0zXteVbAuLlNJqP/W6KVME7ik1WVxSO1kqRfaA6Rk3+XT3TMc2Zfkl9Qw397KpuftnlNb52AWTvrJ39SHAWz4xYhYl5RJ5+BdlOBsziWDQN+kmWVBOXe21jnQV7zGGcQibv9Wo3NGjUYBcj5WhcZJ0s0KVqPp9oP2LAteaamqnBhdkMUwYvlU4Lg0xCHnRRJS8uatkMEKZ22D4UBi1stjCUMyq3ZclbsjoILHGMxNDygW39LBSNCbCYcM716b7G2LNS+74=
    on:
      tags: true

matrix:
  include:
    - python: 2.7
