language: python
python:
- '2.7'
env:
  global:
  - COPR_REPOSITORY=soscleaner
  - OS_ARCH=x86_64
  - DOCKER_IMAGE=alectolytic/rpmbuilder
  - SOSCLEANER_VERSION=$(grep current_version setup.cfg | cut -d \= -f 2 | xargs)
  - TRAVIS_TAG=v${SOSCLEANER_VERSION}
  matrix:
  - OS_TYPE=centos OS_DIST=epel OS_VERSION=7 OS_SLUG=el7
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_447a8e6ecb5b_key -iv $encrypted_447a8e6ecb5b_iv
  -in .copr.enc -out .copr -d
install:
- pip install -r requirements.txt
script:
- nosetests --with-coverage
after_success:
- coveralls
- docker run -v ${PWD}:/sources -v ${PWD}:/output:Z -e "SRPM_ONLY=1" ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}
- copr-cli --config .copr build -r ${OS_DIST}-${OS_VERSION}-${OS_ARCH} ${COPR_REPOSITORY}
  ${COPR_REPOSITORY}-${SOSCLEANER_VERSION}-1.${OS_SLUG}.src.rpm
deploy:
  - provider: releases
    api_key:
      secure: t0qsVHf0YIYg5Ar4vXVIS0VF1pFrriDmnoZWba0dviEu/kIR4U9nXw25j471/LWYN6k8sFM5o1E8LGYEGYxN289YykGwaB740DpJIZRudvTKIwI9BKuv9QXqLt16JR/n8lN/XZLDBGpMNFrTpXBC8zNf6UODy14pdE9b/YiswbtA6685c8ivjHxPbMqfNCXHzCQWvK+CEM6E1m1RDnBq6pTxx2kCuiQayqqybqF0H/ISD0WU6IlDf79Vd5qQXejiLI5VfXfIz4glETfc7hLXkYsKl8TJ6cMEfEYi8ZsQur+kmkgPnwcyb8AV7OPZqbcZqOlbbIXb4xjmCQZDMZcUWj5q3oXyyCOx1ARojkl7JQ02spmT4Pc5q6BDHt0/XJa3AlxcBLq5TyEKD4LpoPnrp5ZlElO/7xOsGOudJbGN/bggN/SjRnSu95WjRhaPsWTWLJ5tAZvSPR3yhLZLtfHiCYDv9vUZ1wk0V1Rdup3yyGB40sJ0mN61GPID81I5Z2qMYyphJrCG8OpbOMrRY5NcW4Cl/g3KZVpGiFPqkixUsBDbMKL4XVyJudOvCMM0q410q7fuSc9e00LSannpgtD5h+twdrqDYGJQZo06ug0v1Uj5wdulhjTzDbalKaQ3Ea33CO5SsoexBla1zMpIFe4ZcyMDXS6hU1KmF7EnvNrTYhA=
    file: soscleaner-${SOSCLEANER_VERSION}.tar.gz
    skip_cleanup: true
    on:
      repo: jduncan-rva/soscleaner
  - provider: pypi
    user: jduncan
    password:
      secure: KD5TenOwsh07lAqdVv2YFuRm8wLErVRyUSo42JHH+K+xlLk3v/c2vfA+9sbwz7wP2sP8MsV9PCageB4WsXDlR7O/2gOBra+G/q5uZtYy62/i0vkqplXdIXg8SC77+h/BgDY+Kw5xwXkzYGGSJXGDLzgBilKexFQ0x9AYAm8UDSmG9EOvecqrd72gwC3zN9tfbpGyPQ/QfMfoKS6CAR1At2A1iZpuGAvHSfx+w1cqKaqJ8KowJ6PSGKKrySnX1vFqqZMGdcyzD64P3aQE7fW8Y/mN9d48tSLmLyPe/a3PqXZ+/rfzoRGpq4bGPQz20FEIT7h/On2fI0ZZuzyMayY1hS3nZCj0+WxvMOj8WPAiGwxEfLne4/M2lVCqUUwsPJilYA43x+0Hsk2vRt/WmXH5rQbIay+DFlLyxrW/rYh6D55QDSxyr2MGjowtLdU0mm54csaB6/8BEvw1mPtStln0JT4+dNKcJpPP/nZaZ5CdighXu7hpccIO+1kmcjZkUi2G+qsUcZ4b9twUve3F5TLCiMQWJfpAHoGvjxz3hUUZ0b4JdpOp6nyUzIo0kbNpOAx14f1IM7k4naQWBy8Zb4fFCBli5BkrWrVol6fD1ohPUI0gry+Don2srfyFUP0F6z/8czXngg2ILGhUe0IagNYySZu+I05XQ8OKnvpv2/Mqz9I=
    server: https://test.pypi.org/legacy/
  - provider: pypi
    user: jduncan
    password:
      secure: "nO5ln4jY6gtwnJZJS5+1G7caiipAn4SBnS9SQzStvterNB9xoBz6pnO0QwvnFwNjD5y3GCqwcVMjmLyY2/+2x01IkZoc5w65FKBuYuvgzf/oIRT/H0VvVZne0+OusBebOzKMoamaCQ3B+kev4xl6v8gr+0l6a8wlmcN5FcHjg1Ee90mYHBRYZU1sOBswwJSFnlPCLM48hq3VYX95iHyypvG22gOhs7fgkouyzoQClhib88xP6S4EHJyAYP7SWgKXiG8JXWMscVbushS/ir9LL/SgW/G/ajwK/HGboIIi8RxndRc8uncXW6mtWneZ5xO65k8whUCwY+tqqHuhsoCa7XLGmCO2JCoz+w8kEUhd87gt5/o0vbGlIHNYyzowglWoF80rMQQDKXzfIJmW2L0khlC3hJgcM8+jy54WeqRZrLS17DE6PvlA3sLqGpXQBOOWY8WaG+/pfmi09OZybgfUu0D8nGPdb506XTXM2EC7afq/+lsjRt34UvZsBDBE7zptSW0SiRTHVgBQLHQZIle7TqyD+XVcCO0Usp30Uv2F4lYmGgWnH9nYpFptOw+YnOqV07cysd5QmU76sUD5izdQ/0Nlfjkf/mcmRyui+AmCvl4Qf6ljkWCTAnpPgDcRkKMM3mUf8k1xtnaSVS24CEsw260tDF9bSO2ZgoNUO7sXuvk="
