language: python
python:
  - "2.7"

script:
  - python setup.py install
  - nosetests --with-coverage

install:
  - pip install -r requirements.txt

deploy:
  - provider: pypi
    user: jduncan
    password:
      secure: KD5TenOwsh07lAqdVv2YFuRm8wLErVRyUSo42JHH+K+xlLk3v/c2vfA+9sbwz7wP2sP8MsV9PCageB4WsXDlR7O/2gOBra+G/q5uZtYy62/i0vkqplXdIXg8SC77+h/BgDY+Kw5xwXkzYGGSJXGDLzgBilKexFQ0x9AYAm8UDSmG9EOvecqrd72gwC3zN9tfbpGyPQ/QfMfoKS6CAR1At2A1iZpuGAvHSfx+w1cqKaqJ8KowJ6PSGKKrySnX1vFqqZMGdcyzD64P3aQE7fW8Y/mN9d48tSLmLyPe/a3PqXZ+/rfzoRGpq4bGPQz20FEIT7h/On2fI0ZZuzyMayY1hS3nZCj0+WxvMOj8WPAiGwxEfLne4/M2lVCqUUwsPJilYA43x+0Hsk2vRt/WmXH5rQbIay+DFlLyxrW/rYh6D55QDSxyr2MGjowtLdU0mm54csaB6/8BEvw1mPtStln0JT4+dNKcJpPP/nZaZ5CdighXu7hpccIO+1kmcjZkUi2G+qsUcZ4b9twUve3F5TLCiMQWJfpAHoGvjxz3hUUZ0b4JdpOp6nyUzIo0kbNpOAx14f1IM7k4naQWBy8Zb4fFCBli5BkrWrVol6fD1ohPUI0gry+Don2srfyFUP0F6z/8czXngg2ILGhUe0IagNYySZu+I05XQ8OKnvpv2/Mqz9I=
    server: https://test.pypi.org/legacy/

  - provider: pypi
    user: jduncan
    password:
      secure: "FUC4b3hcoOvVAe5BXwRLsweHsxznXlVb8R2rxOc8XANDb7TM7X6oOElzl3VO7dYw61WEILIdd7m4shKqRB0WTFACMCegAOUEostDiiEalNufddoypPplsmytsaZ/VzKzNI+gjMemfEvAiQAGQiwF4dYHm9PPfSgIfP/plZi1hrENMSc9kUnmhlZt66230TCsfaJC4wN27hrgL8dXfGF4Q8PvD1+K3dDGwT6vbHCORrfhfQ0Yqj8n7HJXwxhRAPBdKMUv72yxTeDed/JjQdfePBUZHwTJTzCOaXo30B5VMU87uk0SUz+netjFRyxM1bYBuM57CupgPIJIIcItewu6xfkmDIVLoyFJLeFbV5OaSMdsrFYKwGlZfvdiH5cutxSwoRo3xkfh8l2m5GgID/IEV9BKInmhu+SpWGclS4Eh+rdALX2+WuKCNJMsL09A988K155ymNbGv6oVkdxnWfU1pPuXUo4ZXj2Ummz7Fw6Fg19EuIqf9D3Wgv/3YugVr5R4IA4KhM2EH+DqEd81K52C0ODSPk4OQoK6pq3xs9KFMkiuLgrrSJODoR3tWQvxTJt2XfVYM/59kh9V6pzQCfXu/lGfV2kdrCK7KhnrHO2lXw6ddsGf+g+HcG2VqOJgCnj8Qvyjm8sA1uZ/IpGW5Hy+S5s4wajJVkoR/Zvgx/LLaA0="
    on:
      tags: true

after_success:
  - coveralls

matrix:
  include:
  - python: 2.7
