language: python
python:
  - "2.7"

env:
  global:
    - COPR_REPOSITORY=soscleaner
    - OS_ARCH=x86_64
    - SOSCLEANER_VERSION=0.3.15
    - DOCKER_IMAGE=alectolytic/rpmbuilder
  matrix:
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=7
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=28
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=29
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=rawhide

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_447a8e6ecb5b_key -iv $encrypted_447a8e6ecb5b_iv -in .copr.enc -out .copr -d

install:
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage
  - docker run -v ${PWD}:/sources -v ${PWD}:/output:Z -e "SRPM_ONLY=1" ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}

deploy:
  - provider: pypi
    user: jduncan
    password:
      secure: KD5TenOwsh07lAqdVv2YFuRm8wLErVRyUSo42JHH+K+xlLk3v/c2vfA+9sbwz7wP2sP8MsV9PCageB4WsXDlR7O/2gOBra+G/q5uZtYy62/i0vkqplXdIXg8SC77+h/BgDY+Kw5xwXkzYGGSJXGDLzgBilKexFQ0x9AYAm8UDSmG9EOvecqrd72gwC3zN9tfbpGyPQ/QfMfoKS6CAR1At2A1iZpuGAvHSfx+w1cqKaqJ8KowJ6PSGKKrySnX1vFqqZMGdcyzD64P3aQE7fW8Y/mN9d48tSLmLyPe/a3PqXZ+/rfzoRGpq4bGPQz20FEIT7h/On2fI0ZZuzyMayY1hS3nZCj0+WxvMOj8WPAiGwxEfLne4/M2lVCqUUwsPJilYA43x+0Hsk2vRt/WmXH5rQbIay+DFlLyxrW/rYh6D55QDSxyr2MGjowtLdU0mm54csaB6/8BEvw1mPtStln0JT4+dNKcJpPP/nZaZ5CdighXu7hpccIO+1kmcjZkUi2G+qsUcZ4b9twUve3F5TLCiMQWJfpAHoGvjxz3hUUZ0b4JdpOp6nyUzIo0kbNpOAx14f1IM7k4naQWBy8Zb4fFCBli5BkrWrVol6fD1ohPUI0gry+Don2srfyFUP0F6z/8czXngg2ILGhUe0IagNYySZu+I05XQ8OKnvpv2/Mqz9I=
    server: https://test.pypi.org/legacy/
    on:
      condition:
        $OS_TYPE = centos

  - provider: pypi
    user: jduncan
    password:
      secure: "FUC4b3hcoOvVAe5BXwRLsweHsxznXlVb8R2rxOc8XANDb7TM7X6oOElzl3VO7dYw61WEILIdd7m4shKqRB0WTFACMCegAOUEostDiiEalNufddoypPplsmytsaZ/VzKzNI+gjMemfEvAiQAGQiwF4dYHm9PPfSgIfP/plZi1hrENMSc9kUnmhlZt66230TCsfaJC4wN27hrgL8dXfGF4Q8PvD1+K3dDGwT6vbHCORrfhfQ0Yqj8n7HJXwxhRAPBdKMUv72yxTeDed/JjQdfePBUZHwTJTzCOaXo30B5VMU87uk0SUz+netjFRyxM1bYBuM57CupgPIJIIcItewu6xfkmDIVLoyFJLeFbV5OaSMdsrFYKwGlZfvdiH5cutxSwoRo3xkfh8l2m5GgID/IEV9BKInmhu+SpWGclS4Eh+rdALX2+WuKCNJMsL09A988K155ymNbGv6oVkdxnWfU1pPuXUo4ZXj2Ummz7Fw6Fg19EuIqf9D3Wgv/3YugVr5R4IA4KhM2EH+DqEd81K52C0ODSPk4OQoK6pq3xs9KFMkiuLgrrSJODoR3tWQvxTJt2XfVYM/59kh9V6pzQCfXu/lGfV2kdrCK7KhnrHO2lXw6ddsGf+g+HcG2VqOJgCnj8Qvyjm8sA1uZ/IpGW5Hy+S5s4wajJVkoR/Zvgx/LLaA0="
    on:
      tags: true
      condition:
        $OS_TYPE = centos

after_success:
  - coveralls
  - copr-cli --config .copr build -r ${OS_DIST}-${OS_VERSION}-${OS_ARCH} ${COPR_REPOSITORY} ${COPR_REPOSITORY}-${SOSCLEANER_VERSION}-1.el7.src.rpm
